<a href="https://colab.research.google.com/github/taylor-ortiz/pytorch-fundamentals/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

##### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [2]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as python int
scaler.item()

7

In [5]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [37]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0340, 0.2159, 0.5423, 0.9749],
        [0.1240, 0.1707, 0.7850, 0.7318],
        [0.6135, 0.5206, 0.6031, 0.1317]])

In [38]:
# prompt: number of dimensions of random_tensor

random_tensor.ndim


2

In [40]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [16]:
# create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [18]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [19]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors youll run into pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [20]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what data type the tensor is (eg. float32)
                               device=None, # what device is your tensor on? (cpu or gpu)
                               requires_grad=False) # track the gradients when it goes through certain numberical caluclations

In [21]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [23]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

In [24]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, you can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, you can use `tensor.shape`
Tensors not on the right device
3. Tensors not on the right device - to get device from a tensor, you can use `tensor.device`

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3999, 0.7222, 0.0345, 0.0979],
        [0.3698, 0.8535, 0.2140, 0.8227],
        [0.1227, 0.9608, 0.6509, 0.9773]])

In [26]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3999, 0.7222, 0.0345, 0.0979],
        [0.3698, 0.8535, 0.2140, 0.8227],
        [0.1227, 0.9608, 0.6509, 0.9773]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [27]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [30]:
# Try out pytorch built in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication neeeds to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [49]:
torch.matmul(torch.rand(10,10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [31]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [32]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [33]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [41]:
# How long does this take in a traditional for loop?
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.19 ms, sys: 0 ns, total: 1.19 ms
Wall time: 992 µs


tensor(14)

In [42]:
# How long does the matmul operation take?
%%time
torch.matmul(tensor, tensor)

CPU times: user 109 µs, sys: 18 µs, total: 127 µs
Wall time: 133 µs


tensor(14)

In [ ]:
### One of the most common errors in deep learning is shape errors